title: SPHERICAL TECHNOLOGIES # name of the site
author: Giuseppe Silvi # name of site's author
email: info@sphericaltechnologies.net # email of site's author
url: https://www.sphericaltechnologies.net # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog"
description: > # description of the site (multiple lines allowed)
  Spherical Technologies for Omnidirectional Points of Listening

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

# theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please
remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
